### ISSUE TITLE
Request Rejected - Downloading Dataset for Ministry of Health

### ISSUE THREAD

**Issue by hussah-almuzaini** [Esturban/open_ksa#3]
This is an issue I ran into trying to download a dataset from the Ministry of Health. Here is my code:

```python
from open_ksa import get_dataset_resources,get_org_resources

def test_get_dataset_resources():
    # Define the dataset ID to test
    org_id = 'c43616c3-f3ac-41b9-bbad-040670bc396d' #King Saud University
    resources = get_org_resources(org_id=org_id)
    #Here, we grab all of the different dataset_ids
    dataset_ids = resources['dataset_ids']
    #Here, we grab the organization ID as well. But we can use the same organization ID from the ks value
    # we named it ks for 'King Saud University'
    organization_id = resources['organization_id']

    get_dataset_resources(dataset_ids=dataset_ids, 
                         output_dir=f"opendata/{resources['organization_name'].strip().replace(' ', '_').lower()}",
                         allowed_exts=['csv'],
                         verbose=False
                         )

if __name__ == "__main__":
    test_get_dataset_resources()
```

This was my result in excel downloading some dataset:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hussah/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hussah/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

<html><head><title>Request   Rejected</title></head><body>The requested URL was   rejected. Please consult with your administrator.<br><br>Your   support ID is: 6828295494317238133<br><br><a href='javascript:history.back();'>[Go   Back]</a></body></html>
--

</body>

</html>
 
/

**Comment by Esturban** [comment]
@hussah-almuzaini you should now be able to make a call to it. I tested it on python 3.9, 3.10, 3.11 and 3.12. It was two minor details that I didn't know would cause issues. Thank you for reporting it!
